project_id = "qoyawkfbyocgtyxlpgnp"

[functions.approve-request]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.delete-old-notifications]
verify_jwt = false

[functions.parse-supplier-quote]
verify_jwt = false

[functions.reject-request]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-periodic-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.tiryak-ai]
verify_jwt = false

[functions.tiryak-analytics-ai]
verify_jwt = false
